
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/glades/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH 2>/dev/null || true
    - /bin/cp robots.txt $DEPLOYPATH 2>/dev/null || true
    - echo "Deployment completed at $(date)"
    - echo "Ensuring file permissions are correct..."
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - echo "Permissions updated"

