// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlrqbopxslwsfkdaejmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscnFib3B4c2x3c2ZrZGFlam1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODIzOTIsImV4cCI6MjA1OTk1ODM5Mn0.uopXnpYKj8hRFk99l1Bp866gWu4US4FxcFwjJmtK3qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);